### ISSUE TITLE
Load different configuration files

### ISSUE THREAD

**Issue by menduz** [mulesoft-labs/http-bat#26]
## Configuration files

`production.yml`
```yaml
e2e.spec.yml:
  baseUri: http://prod.my-product.com
  only-tags:
    - sanity
  variables:
    organizationId: production-private-org-id
login.spec.yml:
  baseUri: https://auth.my-product.com
```

`local.yml`
```yaml
e2e.spec.yml:
  baseUri: https://dev.local
  variables:
    organizationId: sandbox-org-id
login.spec.yml:
  baseUri: https://dev-auth.local
```

At root level, configuration files contains the target specs as keys (from now an on, described spec).

Within the described spec we MUST be able to specify this fields:

| field | description |
--------------------
| `baseUri` | `string?` overrides the ATL `baseUri` |
| `variables` | `map<any>` after the ATL load all its variables, we deeply merge this object into ATL's variables. Here, `variables` MUST NOT allow the `ENV` key |
| `only-tags` | `string[]` executes only the specified tags. Skipping the non matching ones. |

## ATL Files

`e2e.spec.yml`
```yaml
#%ATL 1.0
baseUri: https://stg.my-product.com
variables:
  ? organizationId

requires:
  login: login.spec.yml

tests:
  "Sanity tests":
    tags: [ sanity ]
    GET /dashboard#unauthorized:
      response:
        status: 401

    GET /dashboard:
      headers:
        Authorization: !!variables login.authToken
      response:
        status: 200
  "Integration":
    tags: [ integration, e2e ]
    POST /assets:
      ...
```

usage `http-bat [spec-file] --config=[config-file] ` -> `http-bat e2e.spec.yml --config=production.yml`
