### ISSUE TITLE
Define tags for tests

### ISSUE THREAD

**Issue by menduz** [mulesoft-labs/http-bat#28]
# Abstract

We should be able to specify tags within tests. In manner to execute a certain of tag, example `sanity` or `end2end` depending on the kind of test we want to run.

Tags may be used on suites and / or tests.

In case `tags` is not defined within a test. It must inherit the tags from the parent suite. Elsewhere it must use only the specified ones.

## Example:

```yaml
#%ATL 1.0

tests:
  "Basic seq":
    tags: [ e2e ]
    GET /executionStatus:
      tags: [ e2e, sanity ]
      response:
        body:
          matches:
            - status: "finished"
```

## Use case:

Sometimes we wrote different files for each kind of test, ex: `sanity.spec.yml` and `e2e.spec.yml`.

And some parts of the code were duplicated. With those tags we are able to differentiate different kinds of tests within the same file in order to run only the selected tags.

```bash
$ http-bat all.spec.yml --tags=sanity --uri=https://production.com
$ http-bat all.spec.yml --tags=e2e --uri=https://dev.local
```

## Checklist:

- [ ] Specification definition
- [ ] Implementation
- [ ] Command line
- [ ] Tests
