### ISSUE TITLE
Test matrix

### ISSUE THREAD

**Issue by menduz** [mulesoft-labs/http-bat#31]
We must be able to perform a test over an endpoint for each element of an array.

On the test runner tree, it must be just one SuiteRunner. The logic must be inside.

Example:

```yaml
tests:
  "Core services":
    matrix:
      - id: test
      - id: qa
      - id: stg

    GET /environments/{$suite.id}/profile/{$test.id}:
      matrix:
        - id: 5
          token: asdasdada
        - id: 3
          token: asddlkfjgnkdjf
        - id: 2
          token: asd83y592r3hq
      headers:
        Authorization: !!variable $test.token
      response:
        status: 200
```

Matrices may be present on suites and tests. Executing the entire suite or test once for each of the elements.

Elements must be stored on a virtual variable `$suite` or `$test` depending on the case.

Matrices may be dynamic or loaded from files too:

Dynamic:
```yaml
tests:
  "Core services":
    GET /users?active=true:
      response:
        status: 200
        body:
          take: !!variable users

    GET /users/{$test.id}:
      matrix: !!variable users
      response:
        status: 200
        body:
          matches:
            - active: true
```

- [ ] Implementation
- [ ] Tests, a lot of
- [ ] Write down the spec

**Comment by fescobar** [comment]
If an array is empty, I wouldn't consider a failed test, because it can be that exist some case where I need to check the empty array. That could be optional. The same could be applied when a matrix's element doesn't pass.

**Comment by menduz** [comment]
In the case you want to check an empty array you could simply do this:

```yaml
GET /items:
  response:
    body:
      matches:
        - length: 0
```

What I'm trying to avoid is 

```yaml
GET /items:
  response:
    body:
      take: !!variable items

GET /items/{$test.id}:
  matrix: !!variable items
  response:
    status: 200
```

- What do we do then `items` is an empty array?
- How shall we assert that exception if it never executes?

@fescobar
