### ISSUE TITLE
Text interpolation

### ISSUE THREAD

**Issue by menduz** [mulesoft-labs/http-bat#36]
The engine must be able to perform text concatenation with variables.

Example

```yaml
#%ATL 1.0

variables:
  token: asd123-3432

tests:
  "Secured token":
    GET /resource:
      header:
        Authorization: "Bearer {token}"
```

Behaviour
On the fields that allows `!!variable` find the double quoted ones with no-scaped curly braces. The apply the same method described in https://github.com/mulesoft/atl#method-uri-interpolation
